services:
  ldap.connection:
    class: ParpV1\LdapBundle\Connection\LdapConnection
    arguments: ['%ad_host%', '%ad_user%', '%ad_password%', '%base_dn%']
  ldap.fetch:
    class: ParpV1\LdapBundle\Service\LdapFetch
    arguments: ['@ldap.connection', '@ldap.ad_user_cache', '@ldap.ad_group_cache']
  ldap.update:
    class: ParpV1\LdapBundle\Service\AdUser\Update\LdapUpdate
    arguments: ['@ldap.fetch', '@ldap.change_compare_service']
  ldap.update_from_entry:
    class: ParpV1\LdapBundle\Service\AdUser\Update\UpdateFromEntry
    arguments: ['@doctrine.orm.entity_manager']
    calls:
      - [setLdapFetch, ['@ldap.fetch']]
      - [setChangeCompareService, ['@ldap.change_compare_service']]
      - [setNewResponseMessagesCollection]
  ldap.update_from_array:
    class: ParpV1\LdapBundle\Service\AdUser\Update\UpdateFromArray
    arguments: ['@doctrine.orm.entity_manager']
    calls:
      - [setLdapFetch, ['@ldap.fetch']]
      - [setChangeCompareService, ['@ldap.change_compare_service']]
      - [setNewResponseMessagesCollection]
  ldap.change_compare_service:
    class: ParpV1\LdapBundle\Service\AdUser\ChangeCompareService
    arguments: ['@doctrine.orm.entity_manager']
  ldap.ad_user_cache:
    class: ParpV1\LdapBundle\Cache\AdUserCache
    arguments: ['@ldap.cache']
  ldap.ad_group_cache:
    class: ParpV1\LdapBundle\Cache\AdGroupCache
    arguments: ['@ldap.cache']
