services:
  ldap.connection:
    class: ParpV1\LdapBundle\Connection\LdapConnection
    arguments: [
      '%ad_host%',
      '%ad_user%',
      '%ad_password%',
      '%base_dc_dn%',
      '%ad_domain%',
      '%base_ou_dn%',
      '%ou_zablokowani%',
      '%ou_nieobecni%'
      ]
  ldap.fetch:
    class: ParpV1\LdapBundle\Service\LdapFetch
    arguments: ['@ldap.connection', '@ldap.ad_user_cache', '@ldap.ad_group_cache']
  ldap.create:
    class: ParpV1\LdapBundle\Service\LdapCreate
    arguments: ['@ldap.connection']
  ldap.update:
    class: ParpV1\LdapBundle\Service\AdUser\Update\LdapUpdate
    arguments: ['@ldap.fetch', '@ldap.change_compare_service', '@doctrine.orm.entity_manager', '@parp.mailer']
  ldap.update_from_entry:
    class: ParpV1\LdapBundle\Service\AdUser\Update\UpdateFromEntry
    arguments: ['@doctrine.orm.entity_manager']
    calls:
      - [setLdapFetch, ['@ldap.fetch']]
      - [setLdapCreate, ['@ldap.create']]
      - [setChangeCompareService, ['@ldap.change_compare_service']]
      - [setNewResponseMessagesCollection]
      - [setEntityManager, ['@doctrine.orm.entity_manager']]
      - [setParpMailerService, ['@parp.mailer']]
      - [setUprawnieniaService, ['@uprawnienia_service']]
      - [setStatusWnioskuService, ['@status_wniosku_service']]
      - [setEntryChain, ['@entry_chain']]
      - [setLogPushChanges, ['@log_push_changes']]
      - [setCurrentUser, ['@security.token_storage']]
  ldap.update_from_array:
    class: ParpV1\LdapBundle\Service\AdUser\Update\UpdateFromArray
    arguments: ['@doctrine.orm.entity_manager']
    calls:
      - [setLdapFetch, ['@ldap.fetch']]
      - [setChangeCompareService, ['@ldap.change_compare_service']]
      - [setNewResponseMessagesCollection]
      - [setEntityManager, ['@doctrine.orm.entity_manager']]
      - [setParpMailerService, ['@parp.mailer']]
  ldap.change_compare_service:
    class: ParpV1\LdapBundle\Service\AdUser\ChangeCompareService
    arguments: ['@doctrine.orm.entity_manager']
  ldap.ad_user_cache:
    class: ParpV1\LdapBundle\Cache\AdUserCache
    arguments: ['@ldap.ad_user.cache']
  ldap.ad_group_cache:
    class: ParpV1\LdapBundle\Cache\AdGroupCache
    arguments: ['@ldap.ad_group.cache']
  ldap.publish_pending_changes_command:
        class: ParpV1\LdapBundle\Command\PublishPendingChangesCommand
        arguments: ['@ldap.update_from_entry']
        tags:
            - { name: 'console.command' }
  entry_chain:
    class: ParpV1\LdapBundle\Service\AdUser\Update\Chain\EntryChain
    arguments: ['@uprawnienia_service', '@status_wniosku_service', '@doctrine.orm.entity_manager', '@parp.mailer']
  publish_voter:
    class: ParpV1\LdapBundle\Voter\AdPublishVoter
    arguments: ['@doctrine.orm.entity_manager']
    tags:
      - { name: security.voter }
    public: false
  log_push_changes:
    class: ParpV1\LdapBundle\Service\LogChanges
    arguments: ['%ad_push_log_directory%', '@templating','%kernel.project_dir%']
