services:
  ldap_connection:
    class: ParpV1\LdapBundle\Service\LdapConnection
    arguments: ['%ad_host%', '%ad_user%', '%ad_password%', '%base_dn%']
  ldap_fetch:
    class: ParpV1\LdapBundle\Service\LdapFetch
    arguments: ['@ldap_connection']
