services:
  edycja_uzytkownika_form_type:
    class: ParpV1\MainBundle\Form\EdycjaUzytkownikaFormType
    arguments: ['@ldap_service', '@user_service']
    tags: [form.type]

  edycja_uzytkownika_service:
        class: ParpV1\MainBundle\Services\EdycjaUzytkownikaService
        arguments: ['@ldap_service', '@doctrine.orm.entity_manager', '@security.token_storage', '%ad_domain%', '%ad_ou%', '%ad_push_delay%']
  ParpV1\MainBundle\Security\Voter\ApplicationActionVoter:
    tags:
      - { name: security.voter }
  zasoby_uzytkownika_grid:
    class: ParpV1\MainBundle\Grid\ZasobyUzytkownikaGrid
    arguments: ['@grid', '@doctrine.orm.entity_manager']
  pracownicy_db_grid:
    class: ParpV1\MainBundle\Grid\PracownicyDbGrid
    arguments: ['@grid']
