imports:
    - { resource: userEditFormPrivileges.yml }

services:
  edycja_uzytkownika_form_type:
    class: ParpV1\MainBundle\Form\EdycjaUzytkownikaFormType
    arguments: ['@ldap_service', '@user_service']
    tags: [form.type]
