stages:
    - build
    - test
    - optional
    - quality

build:
    image: alpine:3.7
    stage: build
    script:
        - apk update
        - apk add curl php5 php5-json php5-phar php5-openssl php5-zlib php5-pdo php5-xml php5-dom php5-ldap php5-ctype php5-intl php5-curl php5-soap
        - echo 'date.timezone = "Europe/Warsaw"' > /etc/php5/conf.d/timezone.ini
        - ln -sf /usr/bin/php5 /usr/bin/php
        - php --ini
        - curl -sS https://getcomposer.org/installer | php
        - php -d memory_limit=3G composer.phar global require "hirak/prestissimo" --prefer-dist --no-suggest --no-progress
        - php -d memory_limit=3G composer.phar install --prefer-dist --no-suggest --no-progress --no-interaction
        - php -d memory_limit=3G composer.phar require "squizlabs/php_codesniffer:~2.2.0" "allocine/twigcs:1.0.*" "sebastian/phpcpd:1.4.*" "phploc/phploc" --prefer-dist --no-suggest --no-progress --no-scripts
        - apk add nodejs nodejs-npm
        - npm init -y
        - npm install eslint eslint-plugin-html eslint-config-idiomatic htmllint-cli

    artifacts:
        untracked: true
        paths:
            - vendor/
            - web/
            - bin/
            - node_modules/

cs_psr2:
    image: alpine:3.7
    stage: test
    script:
        - apk update
        - apk add php5
        - ln -sf /usr/bin/php5 /usr/bin/php
        - ./bin/phpcs -n --report=full --colors --standard=PSR2 --extensions=php src/ParpV1/

lint_twig:
    image: alpine:3.7
    stage: optional
    allow_failure: true
    script:
        - apk update
        - apk add php5 php5-ctype
        - ln -sf /usr/bin/php5 /usr/bin/php
        - ./bin/twigcs lint app/Resources/views/
        - ./bin/twigcs lint src/ParpV1/

lint_js:
    image: alpine:3.7
    stage: optional
    allow_failure: true
    script:
        - apk update
        - apk add nodejs
        - node_modules/.bin/eslint --config .eslintrc --ignore-path .eslintignore --ext .html,.html.twig,.js --format table --color src/ParpV1/
        - node_modules/.bin/eslint --config .eslintrc --ignore-path .eslintignore --ext .html,.html.twig,.js --format table --color app/Resources/views/

lint_html:
    image: alpine:3.7
    stage: optional
    allow_failure: true
    script:
        - apk update
        - apk add nodejs
        - node_modules/.bin/htmllint --rc .htmllintrc src/ParpV1/**/*.html.twig

php_cpd:
    image: alpine:3.7
    stage: quality
    allow_failure: true
    script:
        - apk update
        - apk add php5 php5-iconv
        - ln -sf /usr/bin/php5 /usr/bin/php
        - ./bin/phpcpd src/ParpV1/

php_loc:
    image: alpine:3.7
    stage: quality
    allow_failure: true
    script:
        - apk update
        - apk add php5
        - ln -sf /usr/bin/php5 /usr/bin/php
        - ./bin/phploc src/ParpV1/
