stages:
    - build
    - test

build:
    image: alpine:3.7
    stage: build
    script:
        - apk update
        - apk add curl php5 php5-json php5-phar php5-openssl php5-zlib php5-pdo php5-xml php5-dom php5-ldap php5-ctype php5-intl php5-curl php5-soap
        - echo 'date.timezone = "Europe/Warsaw"' > /etc/php5/conf.d/timezone.ini
        - ln -sf /usr/bin/php5 /usr/bin/php
        - php --ini
        - curl -sS https://getcomposer.org/installer | php
        - php -d memory_limit=3G composer.phar global require "hirak/prestissimo" --prefer-dist --no-progress
        - php -d memory_limit=3G composer.phar install --prefer-dist --no-progress --no-interaction
        - php -d memory_limit=3G composer.phar require "squizlabs/php_codesniffer:~2.2.0" --prefer-dist --no-progress
    artifacts:
        untracked: true
        paths:
            - vendor/
            - web/
            - bin/

cs_psr2:
    # https://github.com/squizlabs/PHP_CodeSniffer
    image: alpine:3.7
    stage: test
    allow_failure: true
    script:
        - apk update
        - apk add php5
        - ln -sf /usr/bin/php5 /usr/bin/php
        - ./bin/phpcs -n --report=full --colors --standard=PSR2 --extensions=php src/ParpV1/
