stages:
    - build
    - test
    - quality
    - stats
    - doc

build:
    image: gitlab.parp.gov.pl:4567/parp/aktywny_dyrektor:latest
    stage: build
    script:
        - /usr/bin/composer.phar global show -i > .gitlab-ci/gitlab-ci-composer.dump
        - php -d memory_limit=5G /usr/bin/composer.phar install --prefer-dist --no-suggest --no-progress --no-interaction
    artifacts:
        expire_in: 1 day
        untracked: true
        paths:
            - vendor/
            - .gitlab-ci/gitlab-ci-composer.dump

parallellint:
    image: gitlab.parp.gov.pl:4567/parp/aktywny_dyrektor:latest
    stage: quality
    allow_failure: false
    script:
        - /root/.composer/vendor/bin/parallel-lint --version
        - /root/.composer/vendor/bin/parallel-lint --colors --blame ./src
        - /root/.composer/vendor/bin/parallel-lint --colors --blame ./app
        - /root/.composer/vendor/bin/parallel-lint --colors --blame ./web

psr2:
    image: gitlab.parp.gov.pl:4567/parp/aktywny_dyrektor:latest
    stage: quality
    allow_failure: false
    script:
        - /root/.composer/vendor/bin/phpcs -n --colors --report=full --standard=PSR2 --extensions=php src/

twigcs:
    image: gitlab.parp.gov.pl:4567/parp/aktywny_dyrektor:latest
    stage: quality
    allow_failure: true
    script:
        - /root/.composer/vendor/bin/twigcs lint app/Resources/views/
        - /root/.composer/vendor/bin/twigcs lint src

eofemptyline:
    image: gitlab.parp.gov.pl:4567/parp/aktywny_dyrektor:latest
    stage: quality
    allow_failure: true
    script:
        - /usr/bin/missing_empty_line_detector.sh -e "./vendor, ./web/bower_components, ./.gitignore" .

phpmd:
    image: gitlab.parp.gov.pl:4567/parp/aktywny_dyrektor:latest
    stage: quality
    allow_failure: true
    script:
        - /root/.composer/vendor/bin/phpmd src/ text "./.gitlab-ci/phpmd.xml"

phpcpd:
    image: gitlab.parp.gov.pl:4567/parp/aktywny_dyrektor:latest
    stage: quality
    allow_failure: true
    script:
        - /root/.composer/vendor/bin/phpcpd src/

phploc:
    image: gitlab.parp.gov.pl:4567/parp/aktywny_dyrektor:latest
    stage: stats
    allow_failure: true
    script:
        - /root/.composer/vendor/bin/phploc src

eslint:
    image: gitlab.parp.gov.pl:4567/parp/aktywny_dyrektor:latest
    stage: quality
    allow_failure: true
    script:
        - /usr/bin/node_modules/bin/eslint --config "./.gitlab-ci/.eslintrc" --ignore-path "./.gitlab-ci/.eslintignore" --ext .html,.html.twig,.js --format table --color "./src/ParpV1/**"
        - /usr/bin/node_modules/bin/eslint --config "./.gitlab-ci/.eslintrc" --ignore-path "./.gitlab-ci/.eslintignore" --ext .html,.html.twig,.js --format table --color "./app/Resources/views/**"

tidyhtml:
    image: gitlab.parp.gov.pl:4567/parp/aktywny_dyrektor:latest
    stage: quality
    allow_failure: true
    script:
        - tidy --gnu-emacs true --doctype omit -e ./src/ParpV1/*
        - tidy --gnu-emacs true --doctype omit -e ./app/Resources/views/*

# lint_html:
#     image: gitlab.parp.gov.pl:4567/parp/aktywny_dyrektor:latest
#     stage: quality
#     allow_failure: true
#     script:
#         - /usr/bin/node_modules/bin/htmllint --rc "./.gitlab-ci/.htmllintrc" src/ParpV1/**/*.{htm,html,html.twig} 
#         - /usr/bin/node_modules/bin/htmllint --rc "./.gitlab-ci/.htmllintrc" app/Resources/views/**/*.{htm,html,html.twig}

sami:
    image: gitlab.parp.gov.pl:4567/parp/aktywny_dyrektor:latest
    stage: doc
    allow_failure: true
    script:
        - mkdir -p doc/api
        - php -d memory_limit=1G /usr/bin/sami.phar update "./.gitlab-ci/sami.conf" -v
    artifacts:
        untracked: false
        expire_in: 1 day
        paths:
            - .gitlab-ci/doc/api/
