stages:
    - build
    - test
    - quality
    - stats
    - doc
    - postbuild

build:
    image: "gitlab-test.parp.gov.pl:5055/aktywny_dyrektor:latest"
    stage: build
    script:
        - /usr/bin/composer.phar global show -i > .gitlab-ci/gitlab-ci-composer.dump
        - php -d memory_limit=5G /usr/bin/composer.phar install --prefer-dist --no-suggest --no-progress --no-interaction
    artifacts:
        expire_in: 1 day
        untracked: true
        paths:
            - vendor/
            - .gitlab-ci/gitlab-ci-composer.dump

parallellint:
    image: "gitlab-test.parp.gov.pl:5055/aktywny_dyrektor:latest"
    stage: quality
    allow_failure: false
    script:
        - /root/.composer/vendor/bin/parallel-lint --version
        - /root/.composer/vendor/bin/parallel-lint --colors --blame ./src
        - /root/.composer/vendor/bin/parallel-lint --colors --blame ./app
        - /root/.composer/vendor/bin/parallel-lint --colors --blame ./web

psr2:
    image: "gitlab-test.parp.gov.pl:5055/aktywny_dyrektor:latest"
    stage: quality
    allow_failure: false
    script:
        - /root/.composer/vendor/bin/phpcs -n --colors --report=full --standard=PSR2 --extensions=php src/

twigcs:
    image: "gitlab-test.parp.gov.pl:5055/aktywny_dyrektor:latest"
    stage: quality
    allow_failure: false
    script:
        - /root/.composer/vendor/bin/twigcs lint app/Resources/views/
        - /root/.composer/vendor/bin/twigcs lint src

neleof:
    image: "gitlab-test.parp.gov.pl:5055/aktywny_dyrektor:latest"
    stage: quality
    allow_failure: true
    script:
        - /usr/bin/neleof.sh -e "./vendor, ./web/bower_components, ./.gitignore" .

phpmd:
    image: "gitlab-test.parp.gov.pl:5055/aktywny_dyrektor:latest"
    stage: quality
    allow_failure: true
    script:
        - /root/.composer/vendor/bin/phpmd src/ text "./.gitlab-ci/phpmd.xml"

phpcpd:
    image: "gitlab-test.parp.gov.pl:5055/aktywny_dyrektor:latest"
    stage: quality
    allow_failure: true
    script:
        - /root/.composer/vendor/bin/phpcpd src/

phploc:
    image: "gitlab-test.parp.gov.pl:5055/aktywny_dyrektor:latest"
    stage: stats
    allow_failure: true
    script:
        - /root/.composer/vendor/bin/phploc src

eslint:
    image: "gitlab-test.parp.gov.pl:5055/aktywny_dyrektor:latest"
    stage: quality
    allow_failure: true
    script:
        - /usr/bin/node_modules/bin/eslint --config "./.gitlab-ci/.eslintrc.json" --ext ".js,.html,.html.twig" --format "table" --color "./src/ParpV1/"
        - /usr/bin/node_modules/bin/eslint --config "./.gitlab-ci/.eslintrc.json" --ext ".js,.html,.html.twig" --format "table" --color "./app/Resources/views/"

tidyhtml:
    image: "gitlab-test.parp.gov.pl:5055/aktywny_dyrektor:latest"
    stage: quality
    allow_failure: true
    script:
        - tidy --gnu-emacs true --doctype omit -e ./src/ParpV1/*
        - tidy --gnu-emacs true --doctype omit -e ./app/Resources/views/*

sami:
    image: "gitlab-test.parp.gov.pl:5055/aktywny_dyrektor:latest"
    stage: doc
    allow_failure: true
    script:
        - mkdir -p doc/api
        - php -d memory_limit=1G /usr/bin/sami.phar update "./.gitlab-ci/sami.conf" -v
    artifacts:
        untracked: false
        expire_in: 1 day
        paths:
            - .gitlab-ci/doc/api/

automerge:
    image: "gitlab-test.parp.gov.pl:5055/aktywny_dyrektor:latest"
    stage: postbuild
    allow_failure: false
    script:
        - echo "machine gitlab.parp.gov.pl login ci_automerge password $pass" > ~/.netrc
        - chmod 600  ~/.netrc
        - git config --global user.name "Merging Bot"
        - git config --global user.email "linuxadmin@parp.gov.pl"
        - mkdir automerge && cd automerge
        - git clone -b development https://gitlab.parp.gov.pl/parp/aktywny_dyrektor.git
        - cd aktywny_dyrektor
        - git fetch origin master
        - git merge --no-ff -m "Auto merge by GitLab-CI job." origin/master
        - git push origin development
    only:
      refs:
        - master
    when: manual
