imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

parameters:
    ad_host: 10.0.2.21
    ad_host2: 10.0.2.21
    ad_host3: 10.0.2.21
    ad_domain: AD.TEST
    ad_user:   aktywny_dyrektor
    ad_password : F4UCorsair
#    ad_ou : "OU=ADUsers"
    ad_ou : "OU=Zespoly, OU=PARP Pracownicy"
#    ad_host: 10.10.16.21
#    ad_host: srv-adc01.parp.local
#    ad_domain: parp.local
#    ad_user:   aktywny_dyrektor
#    ad_password : Gq32hr9cAL
    
