imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com
parameters:
    ad_host: 10.0.2.21
    ad_host2: 10.0.2.21
    ad_host3: 10.0.2.21
    ad_domain: AD.TEST
    ad_user:   aktywny_dyrektor
    ad_password : F4UCorsair
#    ad_ou : "OU=ADUsers"
    ad_ou : "OU=Zespoly, OU=PARP Pracownicy"
#    ad_host: 10.10.16.21
#    ad_host: srv-adc01.parp.local
#    ad_domain: parp.local
#    ad_user:   aktywny_dyrektor
#    ad_password : Gq32hr9cAL
  
