parp_cron:
    resource: "@ParpCronBundle/Controller/"
    type:     annotation
    prefix:   /

parp_main:
    resource: "@ParpMainBundle/Controller/"
    type:     annotation
    prefix:   /

parp_soap:
    resource: "@ParpSoapBundle/Controller/"
    type:     annotation
    prefix:   /

parp_auth:
      resource: "@ParpAuthBundle/Controller/"
      type:     annotation
      prefix:   /

parp_ldap:
    resource: "@ParpLdapBundle/Controller/"
    type:     annotation
    prefix:   /ldap

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
