parp_cron:
    resource: "@ParpCronBundle/Controller/"
    type:     annotation
    prefix:   /

parp_main:
    resource: "@ParpMainBundle/Controller/"
    type:     annotation
    prefix:   /

parp_soap:
    resource: "@ParpSoapBundle/Controller/"
    type:     annotation
    prefix:   /

parp_auth:
      resource: "@ParpAuthBundle/Controller/"
      type:     annotation
      prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"