security:
    encoders:
        Parp\AuthBundle\Security\ParpUser:
            algorithm:   plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        parp:
            id: parp_user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: /login$|/images$
            security: false
        zgloszenie_bledu:
                pattern:  ^/zgloszenie
                security: false
        secured_area:
            pattern:    ^/
            anonymous: false
            remember_me: false
            form_login:
                login_path:  /login
                check_path:  /login_check
                always_use_default_target_path: true
                default_target_path: /index
                username_parameter: _username
                password_parameter: _password
            logout:
                path:   /logout
                target: /login

    access_control:
