security:
    erase_credentials:    true
    encoders:
        ParpV1\AuthBundle\Security\ParpUser:
            algorithm:   plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        parp:
            id: parp_user_provider

    firewalls:
        test_bss:
            pattern:  ^/dev/test_bss
            security: false
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: /login$|/images$
            security: false
        zgloszenie_bledu:
                pattern:  ^/zgloszenie
                security: false
#         RaportyKadrowe_temp:
#                 pattern:  ^/RaportyKadrowe/generujRaportKamil
#                 security: false
        import_rekord2:
                pattern:  ^/import_rekord2
                security: false
        rest_api:
                pattern:  ^/api
                security: false
        usersAdData:
                pattern:  ^/usersAdData
                security: false
        secured_area:
            pattern:    ^/
            anonymous: false
            remember_me: false
            form_login:
                login_path:  /login
                check_path:  /login_check
                always_use_default_target_path: true
                default_target_path: /wnioseknadanieodebraniezasobow/index
                username_parameter: _username
                password_parameter: _password
            logout:
                path:   /logout
                target: /login
            logout_on_user_change: true

    access_control:
