<?php

namespace Parp\MainBundle\Entity;

/**
 * KomentarzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DaneRekordRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByNotHavingRekordIds($ids){
        
        $query = $this->createQueryBuilder('dr')
          ->where('dr.symbolRekordId NOT IN ('.implode(", ", $ids).')')
          ->getQuery();
        
        
        return $query->getResult();
        
    }
    public function findNewPeople(){
        
        if($_SERVER['REMOTE_ADDR'] == "10.10.50.1"){
            $result = $this
               ->createQueryBuilder('e')
               ->select('e')
               ->andWhere("e.newUnproccessed > 0 or e.id = 529")
               ->orderBy("e.newUnproccessed")
               ->getQuery()
               ->getResult(/* \Doctrine\ORM\Query::HYDRATE_ARRAY */);
        }else{
            $result = $this
               ->createQueryBuilder('e')
               ->select('e')
               ->andWhere("e.newUnproccessed > 0")
               ->orderBy("e.newUnproccessed")
               ->getQuery()
               ->getResult(/* \Doctrine\ORM\Query::HYDRATE_ARRAY */);
        }
//               var_dump($result);
        return $result;
    }
}
