<?php

namespace Parp\MainBundle\Entity;

/**
 * DepartamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartamentRepository extends \Doctrine\ORM\EntityRepository
{
    public function bierzDepartamentyNowe(){
        $depsy = $this->findByNowaStruktura(1);
        $ret = [];
        foreach($depsy as $d){
            $ret[$d->getNameInRekord()] = $d;
        }
        return $ret;
    }

}