<?php

namespace Parp\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends EntityRepository
{

    public function findByIsImplementedAndFromWhen()
    {
        $query = $this->createQueryBuilder('e')
                ->where('e.isImplemented = false')
                ->andWhere('e.fromWhen <= :date')
                ->setParameters(array('date' => new \DateTime()))
                ->getQuery();

        return $query->getResult();
    }

}
