<?php

namespace Parp\MainBundle\Entity;

/**
 * KomentarzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KomentarzRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentCount($obiekt, $obiektId)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->select('count(t.id)');
        $qb->where('t.obiekt = :obiekt');
        $qb->andWhere('t.obiektId = :obiektId');
        $qb->setParameter('obiekt', $obiekt);
        $qb->setParameter('obiektId', $obiektId);
    
        return $qb->getQuery()->getSingleScalarResult();
    }
}
