<?php

namespace Parp\MainBundle\Entity;

/**
 * KomentarzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KomentarzRepository extends \Doctrine\ORM\EntityRepository
{
}
