<?php

namespace Parp\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserEngagementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEngagementRepository extends EntityRepository
{

    public function findOneByCryteria($samaccountname = null, $engagement = null, $month = null, $year = null)
    {

        $query = $this->createQueryBuilder('ue')
                ->where('ue.samaccountname = :samaccountname')
                ->andWhere('ue.month = :month')
                ->andWhere('ue.year = :year')
                ->andWhere('ue.engagement = :engagement')
                ->setParameters(array('samaccountname' => $samaccountname, 'engagement' => $engagement, 'month' => $month, 'year' => $year))
                ->getQuery();

        return $query->getOneOrNullResult();
    }

    public function findBySamaccountnameAndYear($samaccountname = null, $year = null)
    {

        $query = $this->createQueryBuilder('ue')
                ->where('ue.samaccountname = :samaccountname')
                ->andWhere('ue.year = :year')
                ->addOrderBy('ue.engagement', 'ASC') ->addOrderBy('ue.month', 'ASC')
                ->setParameters(array('samaccountname' => $samaccountname, 'year' => $year))
                ->getQuery();

        return $query->getResult();
    }
}
