<?php

namespace Parp\MainBundle\Entity;

/**
 * WniosekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WniosekRepository extends \Doctrine\ORM\EntityRepository
{
}
