<?php

namespace Parp\MainBundle\Entity;

/**
 * WniosekNadanieOdebranieZasobowStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WniosekNadanieOdebranieZasobowStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
