<?php

namespace Parp\MainBundle\Entity;

/**
 * WniosekHistoriaStatusowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WniosekHistoriaStatusowRepository extends \Doctrine\ORM\EntityRepository
{
}
