<?php

namespace Parp\MainBundle\Entity;

/**
 * WniosekNadanieOdebranieZasobowEditorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WniosekNadanieOdebranieZasobowEditorRepository extends \Doctrine\ORM\EntityRepository
{
}
