<?php

namespace Parp\MainBundle\Entity;

/**
 * WniosekStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WniosekStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
