<?php

namespace Parp\MainBundle\Entity;

/**
 * WniosekNumerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WniosekNumerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNextNumer($typ, $rok){
        $qb = $this->_em->createQueryBuilder();
        $qb->select('f')
            ->from('ParpMainBundle:WniosekNumer', 'f')
            ->where('f.typWniosku = :typ')
            ->andWhere('f.rok = :rok')
            ->addOrderBy('f.numer',  'DESC')
            ->setParameters(array('typ' => $typ, 'rok' => $rok));
        $res = $qb->getQuery()->getResult();
        if(empty($res)){
            $numer = new WniosekNumer();
            $numer->setNumer(1);            
        }else{
            $numer = new WniosekNumer();
            $numer->setNumer($res[0]->getNumer() + 1);
        }
        $numer->setRok($rok);
        $numer->setTypWniosku($typ);
        //\Doctrine\Common\Util\Debug::dump($numer);
        return $numer;
    }
}
