<?php

namespace Parp\MainBundle\Entity;

/**
 * WniosekViewerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WniosekViewerRepository extends \Doctrine\ORM\EntityRepository
{
}
