<?php

namespace Parp\MainBundle\Entity;

/**
 * WniosekEditorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WniosekEditorRepository extends \Doctrine\ORM\EntityRepository
{
}
