<?php

namespace Parp\MainBundle\Entity;

/**
 * WniosekNadanieOdebranieZasobowViewerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WniosekNadanieOdebranieZasobowViewerRepository extends \Doctrine\ORM\EntityRepository
{
}
