<?php

namespace Parp\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZastepstwoRepository extends EntityRepository
{
    /**
     * @param $samaccountname
     *
     * @return array
     */
    public function znajdzZastepstwa($samaccountname){
        $qb = $this->_em->createQueryBuilder();
        $now = new \Datetime();
        $qb->select('z')
            ->from('ParpMainBundle:Zastepstwo', 'z')
            ->where('z.ktoZastepuje = :samaccountname')
            ->andWhere('z.dataOd <= :now')
            ->andWhere('z.dataDo >= :now')
            ->setParameters(array('samaccountname' => $samaccountname, 'now' => $now));

        return $qb->getQuery()->getResult();
    }

    /**
     * @param $samaccountname
     *
     * @return array
     */
    public function znajdzKogoZastepuje($samaccountname){
        $res = $this->znajdzZastepstwa($samaccountname);
        $ret = [$samaccountname];
        foreach($res as $z){
            $ret[] = $z->getKogoZastepuje();
        }
        return $ret;
    }
}