<?php

namespace ParpV1\JasperReportsBundle\Repository;

use Symfony\Component\VarDumper\VarDumper;
use Doctrine\ORM\Query;
use Doctrine\Common\Collections\ArrayCollection;
use ParpV1\JasperReportsBundle\Fetch\JasperReportFetch;

/**
 * RolePrivilegeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolePrivilegeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Zwraca id ról dostępnych do użycia.
     *
     * @return array
     */
    public function findUsedRoles(): array
    {
        $queryBuilder = $this->createQueryBuilder('r');

        $queryBuilder
            ->select('rl.id')
            ->join('r.role', 'rl');
        ;

        $result = $queryBuilder
            ->getQuery()
            ->getResult(Query::HYDRATE_SCALAR);

        return array_map('reset', $result);
    }

    /**
     * Zwraca ścieżki do raportów na podstawie ról użytkownika.
     *
     * @param array $roles
     *
     * @return array
     */
    public function findPathsByRoles(array $roles, JasperReportFetch $jasperReportFetch): array
    {
        $queryBuilder = $this->createQueryBuilder('r');
        $queryBuilder
            ->select('r, p')
            ->join('r.paths', 'p')
            ->join('r.role', 'rl')
            ->where('rl.name IN(:roles)')
            ->setParameter('roles', $roles)
        ;

        $result = $queryBuilder
            ->getQuery()
            ->getArrayResult()
        ;

        $availablePaths = new ArrayCollection();
        foreach ($result as $rolePrivilege) {
            foreach ($rolePrivilege['paths'] as $path) {
                    $availablePaths->add($path);
            }
        }

        $folderChildren = new ArrayCollection();
        foreach ($availablePaths as $path) {
            if ($path['isRepository']) {
                $folderChildren = $jasperReportFetch
                    ->findAllFromFolderUrl($path['url'])
                ;

                $availablePaths->removeElement($path);
            }
        }

        $mergedCollection = new ArrayCollection(array_merge($availablePaths->toArray(), $folderChildren->toArray()));
        $uniqueCollection = new ArrayCollection();
        foreach ($mergedCollection as $path) {
            $exists = $uniqueCollection->exists(function ($key, $element) use ($path) {
                return $path['url'] === $element['url'];
            });

            if (!$exists) {
                $uniqueCollection->add($path);
            }
        }

        return $uniqueCollection->toArray();
    }
}
