<?php

namespace ParpV1\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends EntityRepository
{
    public function findNowaSekcjaTYLKOuzywaneWreorganizacji2016($sam)
    {
        $query = $this->createQueryBuilder('e')
                ->where('e.isImplemented = false')
                ->andWhere('e.samaccountname like :sam')
                ->andWhere("(e.info not like '' and e.info is not null)")
                ->setParameters(array('sam' => $sam))
                ->getQuery();
        $ret = $query->getResult();
        return $ret;
    }

    public function findByIsImplementedAndFromWhen($ids = "")
    {
        $where = "1 = 1";
        if ($ids != "") {
            $where = 'e.id IN ('.$ids.')';
        }
        $query = $this->createQueryBuilder('e')
                ->where('e.isImplemented = false')
                ->andWhere('e.fromWhen <= :date')
                ->andWhere('e.samaccountname != \'\'')
                ->andWhere($where)
                //->andWhere('e.memberOf = \'\' or e.memberOf is null')
                ->addOrderBy('e.id', 'ASC')
                ->setParameters(array('date' => new \DateTime()))
                ->getQuery();

        return $query->getResult();
    }

    public function getTempEntriesAsUsers($ldap)
    {
        $rets = array();
        $new = $this->findByIsImplementedAndFromWhen();
        foreach ($new as $e) {
            $ADUser = $ldap->getUserFromAD($e->getSamaccountname());

            if (count($ADUser) == 0) {
                $ret = array();
                $ret['id'] = $e->getId();
                $ret['samaccountname'] = $e->getSamaccountname();
                $ret['name'] = $e->getCn();
                $ret['initials'] = $e->getInitials();
                $ret['title'] = $e->getTitle();
                $ret['info'] = $e->getInfo();
                $ret['department'] = $e->getDepartment();
                $ret['description'] = "";
                $ret['division'] = $e->getDivision();
                $ret['lastlogon'] = "";
                $ret['manager'] = $e->getManager();
                $ret['thumbnailphoto'] = "";
                $ret['useraccountcontrol'] = "";

                $ret['accountexpires'] = "";
                $ret['isDisabled'] = $e->getIsDisabled();
                $ret['disableDescription'] = $e->getDisableDescription();
                $ret['accountExpires'] = "";
                $ret['email'] = "";
                $ret['cn'] = "";
                $ret['distinguishedname'] = "";
                $ret['memberOf'] = "";
                $ret['roles'] = "";
                $rets[] = $ret;
            }
        }
        return $rets;
    }
    public function findOsobyKtoreJuzPrzetworzylPrzyOdbieraniu($createdBy)
    {
        $query = $this->createQueryBuilder('e')
                ->select('e.samaccountname')
                ->where('e.isImplemented = 0')
                ->andWhere('e.createdBy in ( :data )')
                ->orderBy('e.id')
                ->setParameters(array('data' => $createdBy))
                ->getQuery();
        $ret = $query->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        $data = [];
        foreach ($ret as $d) {
            if (!in_array($d['samaccountname'], $data)) {
                $data[] = $d['samaccountname'];
            }
        }
        return $data;
    }

    /**
     * Zwraca wszystkie zmiany jakie zaszły na koncie.
     *
     * @todo W przyszłości może być potrzebne pobieranie od daty.
     *
     * @return array
     */
    public function findZmianyNaUzytkownikach()
    {
        $queryBuilder = $this->createQueryBuilder('h');
        $queryBuilder
            ->select('h')
            ->orderBy('h.fromWhen', 'DESC');

        $query = $queryBuilder->getQuery();
        $results = $query->getResult();

        return $results;
    }

    /**
     * Zwraca datę ostatniej zmiany D/B
     *
     * @param  string $samaccountname
     *
     * @return Datetime|null
     */
    public function findZmianaDepartamentuUzytkownika($samaccountname)
    {
/*      Zapytaie testowe:
        select max(fromwhen)
        from entry
        where samaccountname = 'hubert_gorecki'
        and distinguishedname is not null
        group by distinguishedname
        limit 1,1
*/
        $queryBuilder = $this->createQueryBuilder('z');
        $queryBuilder
            ->select('MAX(z.fromWhen) as data_zmiany')
            ->where('z.distinguishedName is not null')
            ->andWhere('z.samaccountname = :samaccountname')
            ->groupBy('z.distinguishedName')
            ->setParameters(array('samaccountname' => $samaccountname))
            ->setFirstResult(1)
            ->setMaxResults(1);

        $query = $queryBuilder->getQuery();
        $dataZmiany = $query->getResult();

        return $dataZmiany;
    }
}
