<?php

namespace ParpV1\MainBundle\Entity;

/**
 * ImportSekcjeUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportSekcjeUserRepository extends \Doctrine\ORM\EntityRepository
{
}
