<?php

namespace ParpV1\MainBundle\Entity;

/**
 * WniosekNadanieOdebranieZasobowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WniosekUtworzenieZasobuRepository extends \Doctrine\ORM\EntityRepository
{
}
