<?php

namespace ParpV1\SoapBundle\Entity;

/**
 * ADGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ADGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
