<?php

namespace ParpV1\SoapBundle\Entity;

/**
 * ADOrganizationalUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ADOrganizationalUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
