<?php

namespace Parp\SoapBundle\Entity;

/**
 * ADUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ADUserRepository extends \Doctrine\ORM\EntityRepository
{
}
