<?php

namespace ParpV1\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AccessLevelGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessLevelGroupRepository extends EntityRepository
{
}
