<?php

namespace ParpV1\MainBundle\Repository;

/**
 * AccessLevelGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessLevelGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
