<?php

namespace ParpV1\MainBundle\Repository;

/**
 * OdebranieZasobowEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OdebranieZasobowEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
