parameters:
  bundle_path: 'ParpV1\JasperReportsBundle'
services:
  jasper.connection:
    class: '%bundle_path%\Connection\JasperConnection'
    arguments: [
      '%jasper_server_url%',
      '%jasper_username%',
      '%jasper_password%',
      '%jasper_request_timeout%'
      ]
  jasper.fetch:
    class: '%bundle_path%\Fetch\JasperFetch'
    arguments: ['@jasper.connection']
  jasper.path_validator:
    class: '%bundle_path%\Validator\Constraints\JasperPathValidator'
    arguments: ['@jasper.fetch']
    tags:
      - { name: 'validator.constraint_validator' }
  jasper.reports_grid:
    class: '%bundle_path%\Grid\JasperReportsGrid'
    arguments: ['@grid', '@doctrine.orm.entity_manager', '@jasper.fetch']
  jasper.paths_grid:
    class: '%bundle_path%\Grid\PathsGrid'
    arguments: ['@grid']
  jasper.report_print:
    class: '%bundle_path%\Printer\ReportPrint'
    arguments: ['@jasper.connection']
  jasper.report_voter:
    class: '%bundle_path%\Voter\ReportVoter'
    arguments: ['@doctrine.orm.entity_manager', '@jasper.fetch']
    tags:
      - { name: security.voter }
  jasper.generate_report_type:
    class: '%bundle_path%\Form\GenerateReportType'
    arguments: ['@jasper.fetch']
    tags: [form.type]
